# Generated by Django 2.2.12 on 2020-06-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLivro', models.CharField(max_length=255)),
                ('categoriaLivro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Livro',
            },
        ),
    ]
